[package]
name = "mxit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
shell-words = "1.1.0"
